all:
	@echo "Building winkey project... empty for now"

clean:
	@echo "Cleaning winkey project... empty for now"

fclean: clean
	@echo "Full clean winkey project... empty for now"

re: fclean all

.PHONY: all clean fclean re